package `in`.mahato.tambola.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.widget.Toast
import androidx.core.content.FileProvider
import `in`.mahato.tambola.rule.entity.WinningPrizeEntity
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfShareUtil {

    fun generateAndShareWinnerPdf(
        context: Context,
        winners: List<WinningPrizeEntity>,
        gameId: String = ""
    ) {
        if (winners.isEmpty()) {
            Toast.makeText(context, "No winners to share!", Toast.LENGTH_SHORT).show()
            return
        }

        try {
            val pdfDocument = PdfDocument()
            val pageWidth = 595 // Standard A4 width in points (72 dpi)
            val pageHeight = 842 // Standard A4 height in points (72 dpi)
            val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
            val page = pdfDocument.startPage(pageInfo)
            val canvas: Canvas = page.canvas

            val titlePaint = Paint().apply {
                color = Color.parseColor("#1B5E20") // Deep Green
                textSize = 22f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                textAlign = Paint.Align.CENTER
            }

            val subtitlePaint = Paint().apply {
                color = Color.DKGRAY
                textSize = 12f
                textAlign = Paint.Align.CENTER
            }

            val headerPaint = Paint().apply {
                color = Color.parseColor("#0D47A1") // Deep Blue
                textSize = 13f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            }

            val textPaint = Paint().apply {
                color = Color.BLACK
                textSize = 12f
            }

            val linePaint = Paint().apply {
                color = Color.LTGRAY
                strokeWidth = 1f
            }

            var currentY = 50f

            // Title
            canvas.drawText("TAMBOLA BOARD - WINNER LIST", (pageWidth / 2).toFloat(), currentY, titlePaint)
            currentY += 24f

            // Date & Game ID Subtitle
            val dateStr = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date())
            val subText = if (gameId.isNotBlank()) "Game ID: $gameId  |  Date: $dateStr" else "Date: $dateStr"
            canvas.drawText(subText, (pageWidth / 2).toFloat(), currentY, subtitlePaint)
            currentY += 30f

            // Table Header Background
            val leftMargin = 35f
            val rightMargin = pageWidth - leftMargin
            val col1 = leftMargin + 10f
            val col2 = 250f
            val col3 = 450f

            canvas.drawRect(leftMargin, currentY, rightMargin, currentY + 28f, Paint().apply {
                color = Color.parseColor("#E3F2FD")
            })

            canvas.drawText("Prize / Rule Name", col1, currentY + 18f, headerPaint)
            canvas.drawText("Winner(s)", col2, currentY + 18f, headerPaint)
            canvas.drawText("Status", col3, currentY + 18f, headerPaint)

            currentY += 28f
            canvas.drawLine(leftMargin, currentY, rightMargin, currentY, linePaint)

            // Table Content
            for (item in winners) {
                currentY += 24f
                val ruleName = item.savedRule.ruleName
                val winnerName = if (item.winnerName.isNullOrEmpty()) "Pending Claim" else item.winnerName!!
                val status = if (item.isClaimed) "Claimed" else "Unclaimed"

                canvas.drawText(ruleName, col1, currentY, textPaint)
                canvas.drawText(winnerName, col2, currentY, textPaint)
                canvas.drawText(
                    status,
                    col3,
                    currentY,
                    Paint(textPaint).apply {
                        color = if (item.isClaimed) Color.parseColor("#2E7D32") else Color.parseColor("#C62828")
                        typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                    }
                )

                currentY += 8f
                canvas.drawLine(leftMargin, currentY, rightMargin, currentY, linePaint)

                // Page Boundary Check
                if (currentY > pageHeight - 80f) break
            }

            // Footer
            val footerPaint = Paint().apply {
                color = Color.GRAY
                textSize = 10f
                textAlign = Paint.Align.CENTER
            }
            canvas.drawText("Generated by Tambola Board App", (pageWidth / 2).toFloat(), pageHeight - 35f, footerPaint)

            pdfDocument.finishPage(page)

            // Save PDF to cache directory
            val pdfFile = File(context.cacheDir, "Tambola_Winners.pdf")
            val outputStream = FileOutputStream(pdfFile)
            pdfDocument.writeTo(outputStream)
            pdfDocument.close()
            outputStream.close()

            // FileProvider URI
            val pdfUri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                pdfFile
            )

            // System ACTION_SEND Intent
            val subjectText = if (gameId.isNotBlank()) "Tambola Winner List (Game Code: $gameId)" else "Tambola Board Winner List"
            val shareMessage = if (gameId.isNotBlank()) {
                "Here is the winner list for Tambola Game Code: $gameId!\n\nAttached is the PDF report."
            } else {
                "Here is the winner list for our Tambola game!\n\nAttached is the PDF report."
            }

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, pdfUri)
                putExtra(Intent.EXTRA_SUBJECT, subjectText)
                putExtra(Intent.EXTRA_TEXT, shareMessage)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(shareIntent, "Share Winner PDF"))
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Error generating PDF: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }
}
